name: 'edge-function-tests'
# on:
#   pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.11.4
      - run: supabase start
      - run: supabase functions serve
      - run: deno test --allow-all deno-test.ts --env-file .env.local
